# Site settings
title: Pierre Louchet
email: pierre.louchet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hellfar.github.io" # the base hostname & protocol for your site
# twitter_username: Hellfar
github_username:  Hellfar

# Build settings
markdown: redcarpet
highlighter: pygments
pygments_options: ['lineanchors', 'linenos=table']
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed
