# Site settings
name: hellfar.github.io
authors: Pierre Louchet
title: Pierre Louchet
email: pierre.louchet@gmail.com
keywords: Hellfar, hellfar, Pierre, pierre, Louchet, louchet, Pierre Louchet, pierre louchet, pierrelouchet, profil
description: > # this means to ignore newlines until "baseurl:"
  I am an enthusiastic Information Tech student from Epitech, a school that pushes toward innovation.
  I love discover new technology and technique which make me able to express creativity and skills.
  Thus, I would say that I am a learner.

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://hellfar.github.io" # the base hostname & protocol for your site
# twitter_username:  Hellfar
github_username:         Hellfar
linkedin_username:       pierrelouchet
stack-overflow_username: 5384061/hellfar
codeschool_username:     2291772

# Build settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude: ["_exclude","watch.sh"]

markdown: kramdown
highlighter: pygment
pygments_options: ['lineanchors', 'linenos=table']
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

- jekyll-sass-converter
- jekyll-paginate

sass:
  sass_dir: ['_sass', 'lib']
  style: compressed
